# Generated by Django 5.0 on 2024-01-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskPlanner', '0002_task_emoji_task_emotion_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='emoji',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
