# Generated by Django 5.0 on 2024-01-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskPlanner', '0003_alter_task_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='emoji',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
